services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    environment:
      - caminho_arquivo_modelo=/app/modelo_heart_disease.pmml
      - server_port=8091