services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: agendamentos
      POSTGRES_PASSWORD: agendamentos_senha
      POSTGRES_DB: api_agendamentos
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - spring_api_network

volumes:
  postgres_data:

networks:
  spring_api_network:
